### ISSUE TITLE
Is there any functionality for "FlipCoordinates" in ScichartBlazor or we need to Implement?

### ISSUE THREAD

**Issue by dhruvindudhat** [NRTDP/SciChartBlazor#13]
I want to use "FlipCoordinates" Property to flip the Y-axis.
I believe that both ScichartJs and Wpf has this feature. Could someone please provide guidance on how to implement this within the wrapper? If feasible, could you also outline the high-level steps for integrating this functionality or wrapper has a function/property for this?

**Comment by mikehollas123** [comment]
Looks like it's not yet. You should just need to add a FlippedCoordinates property to the AxisBase.cs. I haven't tested it, and I don't think I'll have time to try this anytime soon. 
Hope this helps. If it does, please do a PR and add a quick test to the shared library please.

**Comment by dhruvindudhat** [comment]
`
    /// <summary>
    /// Gets or sets the FlipCoordinate.
    /// </summary>
    public bool FlipCoordinates { get; set; `}``

I have added this and set to true default when adding the Y-axis but looks like it is not Flipping The Coordinates.

**Comment by mikehollas123** [comment]
Hmm. The wrapper uses the builder functionality of scichart js. See if you can get it to work using the scichart js builder directly. The demo website lets you do this on the site. Sometimes the names don't line up and we have to rename it

**Comment by mikehollas123** [comment]
Oh it needs to be "FlippedCoordinates". The names have to match up exactly

**Comment by dhruvindudhat** [comment]
I am not able to push the code or raise a PR for this change. Can you guide?
` /// <summary>
    /// Gets or sets flipped cordinates.
    /// </summary>
    public bool? FlippedCoordinates { get; set; } = null;`

**Comment by mikehollas123** [comment]
Hi sure.
Due to branch protections you can't push directly into main. What you need to do is "fork" this repo. That makes a new copy of this repo in your GitHub. You'll make your changes in that fork. Then when you push to that fork, you'll get the option to do a Pull Request (PR) into the base repo. [guide on how to do that](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

Hope this helps

**Comment by dhruvindudhat** [comment]
Thanks for quick support, Pull request raised. Please check it.
In future if any changes needed I will follow this same process.
